In [13]:
t=('a',111,'b')
print(t)
t=()
print(type(t))
t1=tuple()
print(type(t1))


('a', 111, 'b')
<class 'tuple'>
<class 'tuple'>


In [9]:
t=("a","b","c","d","e")
print(t[-1])

e


In [11]:
lan=('eng','kan','tam')
for i in lan:
    print(i)


eng
kan
tam


In [15]:
t=(2,3,4,5,6,7)
def fact(n):
    f=1
    for i in range(1,n+1):
        f*=i
    return f
for i in t:
    print("Factorial of ",i," is ",fact(i))


Factorial of  2  is  2
Factorial of  3  is  6
Factorial of  4  is  24
Factorial of  5  is  120
Factorial of  6  is  720
Factorial of  7  is  5040


In [51]:
def table(a,n):
    for i in range(1,n+1):
        print(a,"X",i,"=",a*i)
a=int(input("Enter upto num: "))
print("______________________")
for i in range(x):
    if a<=5 and a>=1:
        table(a,5)
    elif a>=6 and a<=10:
        table(a,10)
    elif a>=11 and a<=15:
        table(a,15)
    elif a>=16 and a<=20:
        table(a,20)
    elif a>=21:
        print(a,30)

Enter upto num:  15


______________________
15 X 1 = 15
15 X 2 = 30
15 X 3 = 45
15 X 4 = 60
15 X 5 = 75
15 X 6 = 90
15 X 7 = 105
15 X 8 = 120
15 X 9 = 135
15 X 10 = 150
15 X 11 = 165
15 X 12 = 180
15 X 13 = 195
15 X 14 = 210
15 X 15 = 225
15 X 1 = 15
15 X 2 = 30
15 X 3 = 45
15 X 4 = 60
15 X 5 = 75
15 X 6 = 90
15 X 7 = 105
15 X 8 = 120
15 X 9 = 135
15 X 10 = 150
15 X 11 = 165
15 X 12 = 180
15 X 13 = 195
15 X 14 = 210
15 X 15 = 225
15 X 1 = 15
15 X 2 = 30
15 X 3 = 45
15 X 4 = 60
15 X 5 = 75
15 X 6 = 90
15 X 7 = 105
15 X 8 = 120
15 X 9 = 135
15 X 10 = 150
15 X 11 = 165
15 X 12 = 180
15 X 13 = 195
15 X 14 = 210
15 X 15 = 225
15 X 1 = 15
15 X 2 = 30
15 X 3 = 45
15 X 4 = 60
15 X 5 = 75
15 X 6 = 90
15 X 7 = 105
15 X 8 = 120
15 X 9 = 135
15 X 10 = 150
15 X 11 = 165
15 X 12 = 180
15 X 13 = 195
15 X 14 = 210
15 X 15 = 225
15 X 1 = 15
15 X 2 = 30
15 X 3 = 45
15 X 4 = 60
15 X 5 = 75
15 X 6 = 90
15 X 7 = 105
15 X 8 = 120
15 X 9 = 135
15 X 10 = 150
15 X 11 = 165
15 X 12 = 180
15 X 13 = 195
15 X 14 = 210
15 X 15 = 225
15

In [57]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,1,1],[2,2,2],[3,3,3]])
d=np.ones([2,2])
d1=np.zeros([3,3])
d2=np.random.random([2,2])
print(d)
print(d1)
print(d2)

[[1. 1.]
 [1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0.04074372 0.90881752]
 [0.27700028 0.20067075]]


In [61]:
import numpy as np
x=np.array([[1,1],[2,2]])
y=np.array([[2,2],[1,1]])
print(x+y)

[[3 3]
 [3 3]]


In [65]:
import numpy as np
a=np.array([[1,4,3],[6,7,5],[9,7,8]])
print(np.sort(a,axis=1))
print(np.sort(a,axis=0))
print(np.sort(a,axis=None))

[[1 3 4]
 [5 6 7]
 [7 8 9]]
[[1 4 3]
 [6 7 5]
 [9 7 8]]
[1 3 4 5 6 7 7 8 9]


In [71]:
import numpy as np
a=np.array([1,3,4,2])
print(a.mean())
print(a.std())
print(a.sum())
print(a.min())
print(a.max())

2.5
1.118033988749895
10
1
4


In [73]:
import pandas as pd
d=[1,3,2]
s=pd.Series(d)
print(s)

0    1
1    3
2    2
dtype: int64


In [75]:
import pandas as pd
mydata={
'cars':['BMW','Volvo','Ford'],'passings':[3,4,8]
}
mycar=pd.DataFrame(mydata)
print(mycar)

    cars  passings
0    BMW         3
1  Volvo         4
2   Ford         8
